# Generated by Django 3.1.1 on 2020-10-20 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_auto_20201020_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaClientConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROUNDS_PER_RUN', models.IntegerField(default=5)),
                ('SHUTDOWN_AFTER_RUN', models.BooleanField(default=True)),
                ('DEBUG_MODE', models.BooleanField(default=False)),
                ('PYTHON', models.CharField(default='python3', max_length=10)),
                ('CLEANUP_BETWEEN_ROUNDS', models.BooleanField(default=True)),
                ('SECURE_MODE', models.BooleanField(default=False)),
                ('RUN_PLAYER1_AS_USER', models.CharField(max_length=50)),
                ('RUN_PLAYER2_AS_USER', models.CharField(max_length=50)),
                ('LOGGING_LEVEL', models.IntegerField(default=10)),
                ('MAX_GAME_TIME', models.IntegerField(default=68486)),
                ('MAX_REAL_TIME', models.IntegerField(default=7200)),
                ('MAX_FRAME_TIME', models.IntegerField(default=1000)),
                ('STRIKES', models.IntegerField(default=10)),
                ('REALTIME', models.BooleanField(default=False)),
                ('DISABLE_DEBUG', models.BooleanField(default=True)),
                ('VALIDATE_RACE', models.BooleanField(default=False)),
                ('arenaclient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.arenaclient')),
            ],
        ),
    ]
